using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ProjectEuler
{
    class Problem2
    {
        //Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
        public static void Solve()
        {
            int a = 0;
            int b = 1;
            int temp;
            int sum = 0;

            while (b < 4000000)
            {
                temp = a;
                a = b;
                b = temp + b;

                if (b % 2 == 0)
                    sum += b;
            }
            Console.WriteLine("The sum of the even-valued terms is {0}.", sum);
        }

        public static void FibonacciSeries(int num)
        {
            int a = 0;
            int b = 1;
            int temp;

            for (int i = 0; i < num; i++)
            {
                temp = a;
                a = b;
                b = temp + b;

                Console.WriteLine(b);  // using b prints out the sequence as listed in Project Euler Problem 2
            }
        }

        // This methd uses recursion and a condensed if statement
        public static int Fibonacci(int n)
        {
            return (n < 2) ? n : Fibonacci(n - 1) + Fibonacci(n - 2);
        }     
    }
}
